spring.cloud.gcp.logging.enabled=true

# Cymbal Transit Configuration
# Replace these values with your actual GCP details
GCP_PROJECT_ID=day2-490516
GCP_REGION=us-central1
GEMINI_MODEL_NAME=gemini-2.5-flash
MCP_TOOLBOX_URL=https://toolbox-cymbal-transit-266664366100.us-central1.run.app/mcp
